export const ENV_VARS = {

    AWS: {
        AWS_REGION: 'AWS_REGION',
        AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
        AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
    },
    AWS_COGNITO: {
        AWS_COGNITO_USER_POOL_ID: 'AWS_COGNITO_USER_POOL_ID',
        CLIENT_ID: 'AWS_COGNITO_CLIENT_ID',
        AWS_COGNITO_CLIENT_SECRET:'AWS_COGNITO_CLIENT_SECRET'
    },

}